# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Infomedia editore
login_url: "https://medium.com/l-o-g-i-n"
dev_url: "https://medium.com/developing-software-solutions"
cp_url: "https://medium.com/infomedia-computer-programming"

# Build settings
markdown: kramdown
exclude: [README.md]

